import { Geist, Geist_Mono } from "next/font/google";
//import "bootstrap/dist/css/bootstrap.min.css"
import "./css/main.css"
import "./css/notification.css"
import "./css/globals.css";
import "./css/list-contacts.css"
import FirebaseServiceWorker from "./componentes/ui/workerRegistration";
import { Suspense } from "react";
import { NotificationRouteHandler } from "./componentes/NotificationHandler";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en"
      className={`${geistSans.variable} ${geistMono.variable}`}>

      <body>
        {/* <BootstrapJs /> */}
        <Suspense fallback={null}>
          <NotificationRouteHandler />
        </Suspense>
        <FirebaseServiceWorker />
        {children}
      </body>
    </html>
  );
}
